name=Water Tricorder
version=0.1.0
author=Graphite Design Labs
maintainer=Graphite Design Labs <hello@graphitedesignlabs.com>
sentence=Low-cost opensource water quality assessment device
paragraph=Uses optical microscopy and spectrometry with machine learning to determine water potability. Designed for Arduino Nano 33 BLE.
category=Sensors
url=https://github.com/graphitedesignlabs/WaterTricorder
architectures=mbed_nano
includes=WaterTricorder.ino
depends=Arduino_TensorFlowLite
